version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: /home/CSSI-MCCCS

    steps:
      - checkout
      - run: sudo mkdir -p /home/CSSI-MCCCS
      - run:
          name: install dependencies
          command: |
            python setup.py develop
      - run:
          name: run test
          command: |
            python simple-test.py
