version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python setup.py develop
      - run:
          name: run test
          command: |
            python cssi_mcccs/tests/simple-test.py
